# Set the maximum width for a single line.
#max_width = 130

# Use visual indentation (align with the opening delimiter).
use_small_heuristics = "Max"

# Format string literals where necessary to fit within the line width.
format_strings = true

# Reorder import statements alphabetically.
reorder_imports = true
